---
title: "Peer Review"
---

# Purpose

Peer review is not only essential in the scientific community to check one another's work, but it can also be a great tool in your own learning process. Doing peer review turns you into a serious reader who is trying to understand the main thesis of a piece of writing as well as the arguments. The goal is to provide feedback to help the writer convey their argument in a clear and concise manner.


# Task

There is no one definitive way to do a peer review, but in general you want read someone's work and do the following:

1. **Identify the thesis:** Restate the main argument for the writer. In doing so you can offer a different, more effective phrasing (hopefully, it is the argument the writer wanted to make).
2. **List the major supporting points and evidence:** Create a list of the main points and what evidence the writer offers. At this point, you have distilled their text into the main argument (thesis) and the supporting points.
3. **Identify the most effective/convincing part of the text as well as the least effective:** Tell the writer how effective you think each point is and whether the evidence they provide actually supports their argument.
4. **Think about the order of paragraphs and sentences:** Do the main points seem out of place? Should one come first before the other? Are there sentences that are incomplete or points that need more explanation?


# Using a Peer Tutoring Technique

After many years of working in the writing center (both as an undergraduate and graduate student), I learned one technique that I used to start all of my sessions. This basically consists of asking the writer to do the task above while you read their paper and do the same.

1. Ask the writer to write down the thesis and most important points they are wanting the reader to take away while you read their paper.^[I find this is really useful when thinking about cover letters or grad school applications. At the core, the question you should ask is, *what do I want the reader to remember?*]
2. Read the paper and see if you can quickly identify the thesis, the supporting evidence, and the overall structure.
3. Compare notes with the writer. I often asked the writer to go first and tell me what they were trying to communicate.
    a. If the argument the writer tell us is not what you understood from their paper, tell them and find a way to make the argument clearer. (The argument is clear in the writer's mind but not yet in the paper.)
    b. If the writer cannot tell you a clear argument, it's time to ask questions to help them clarify what they are arguing. (The argument is not yet clear in the writer's mind.)
4. Once the main thesis is clearly articulated, I move on to the supporting points. I ask the writer, what are your main points? After hearing them, I try to locate them in the paper.
    a. Each point should be in the first sentence of a paragraph (the topic sentence).
    b. As a general rule, I suggest the writer presents one point at a time. When you start a new point, start a new paragraph.
5. Sessions usually last no more than 40 minutes. So, before time is up, I ask the writer what they think are the next steps. It's important that they know what the main areas they should focus on are and how to improve them.
    a. The writer will hopefully mention specific areas or thing they need to do. (Your job is done!)
    b. If the writer does not articulate clear next steps, offer some guidance.
6. Offer encouragement. For example, "I agree! I think once you do these things, your argument will be much stronger"




